version: "3"
services:
  ngrok:
    image: wernight/ngrok
    ports:
      - 0.0.0.0:4040:4040
    links:
      - ci_server
    environment:
      NGROK_PORT: ci_server:80
  ci_server:
    build: ./ci_server
    ports:
      - 80:80
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: ./certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: ./certs/domain.key
    volumes:
      - ./certs:/certs
      - ./data:/data
